schema {
    mutation: Mutation
    query: Query
}

type Mutation {
    startRide(bikeId: ID!): RideResponse!
    endRide(rideId: ID!): RideResponse!
}

type Query {
    getUser: UserResponse!

    getBike(id: ID!): BikeResponse!
    listBikes(req: ListBikesRequest!): [BikeResponse]!
}

input ListBikesRequest {
    lat: Float!
    lon: Float!
}

type BikeResponse {
    id: ID!
    lat: Float!
    lon: Float!
    imageUrl: String!
}

type UserResponse {
    id: ID!
    firstName: String!
    lastName: String!
    email: String!
}

type RideResponse {
    id: ID!
    userId: ID!
    bikeId: ID!
    startTime: String!
    endTime: String
}
