include:
  - compose.deps.yml

services:
  gateway:
    build:
      context: gateway
    labels:
      # allow log collection with alloy
      logs.collect: true
    environment:
      SERVICE_ADDRESS: ":8080"

      OTEL_SERVICE_NAME: gateway
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=local"

  users:
    build:
      context: users
    labels:
      # allow log collection with alloy
      logs.collect: true
    environment:
      GRPC_SERVICE_ADDRESS: ":50050"
      DB_CONNECTION_STRING: "postgres://postgres:localDb123@localhost:5432"
      REDIS_ADDRESSES: "localhost:6379"

      OTEL_SERVICE_NAME: users
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=local"

  bikes:
    build:
      context: bikes
    labels:
      # allow log collection with alloy
      logs.collect: true
    environment:
      SERVICE_ADDRESS: "grpc:50051"

      OTEL_SERVICE_NAME: bikes
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=local"

  invoices:
    build:
      context: invoices
    labels:
      # allow log collection with alloy
      logs.collect: true
    environment:

      OTEL_SERVICE_NAME: invoices
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=local"
