// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: bikes/bikes.proto

package bikes

import (
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBikeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBikeByIdRequest) Reset() {
	*x = GetBikeByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBikeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBikeByIdRequest) ProtoMessage() {}

func (x *GetBikeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBikeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBikeByIdRequest) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{0}
}

func (x *GetBikeByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BikeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location *latlng.LatLng `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	ImageUrl string         `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *BikeReply) Reset() {
	*x = BikeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeReply) ProtoMessage() {}

func (x *BikeReply) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeReply.ProtoReflect.Descriptor instead.
func (*BikeReply) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{1}
}

func (x *BikeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BikeReply) GetLocation() *latlng.LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *BikeReply) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ListBikesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bikes []*BikeReply `protobuf:"bytes,1,rep,name=bikes,proto3" json:"bikes,omitempty"`
}

func (x *ListBikesReply) Reset() {
	*x = ListBikesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBikesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBikesReply) ProtoMessage() {}

func (x *ListBikesReply) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBikesReply.ProtoReflect.Descriptor instead.
func (*ListBikesReply) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{2}
}

func (x *ListBikesReply) GetBikes() []*BikeReply {
	if x != nil {
		return x.Bikes
	}
	return nil
}

type SetBikeReservedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SetBikeReservedRequest) Reset() {
	*x = SetBikeReservedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBikeReservedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBikeReservedRequest) ProtoMessage() {}

func (x *SetBikeReservedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBikeReservedRequest.ProtoReflect.Descriptor instead.
func (*SetBikeReservedRequest) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{3}
}

func (x *SetBikeReservedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetBikeReservedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetBikeReservedReply) Reset() {
	*x = SetBikeReservedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBikeReservedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBikeReservedReply) ProtoMessage() {}

func (x *SetBikeReservedReply) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBikeReservedReply.ProtoReflect.Descriptor instead.
func (*SetBikeReservedReply) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{4}
}

type SetBikeAvailableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SetBikeAvailableRequest) Reset() {
	*x = SetBikeAvailableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBikeAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBikeAvailableRequest) ProtoMessage() {}

func (x *SetBikeAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBikeAvailableRequest.ProtoReflect.Descriptor instead.
func (*SetBikeAvailableRequest) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{5}
}

func (x *SetBikeAvailableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetBikeAvailableReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetBikeAvailableReply) Reset() {
	*x = SetBikeAvailableReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBikeAvailableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBikeAvailableReply) ProtoMessage() {}

func (x *SetBikeAvailableReply) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBikeAvailableReply.ProtoReflect.Descriptor instead.
func (*SetBikeAvailableReply) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{6}
}

var File_bikes_bikes_proto protoreflect.FileDescriptor

var file_bikes_bikes_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x1a, 0x1e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x2f, 0x6c, 0x61, 0x74, 0x6c, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x68, 0x0a, 0x09, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2f, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x3b, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x29, 0x0a, 0x05, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x52, 0x05, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x53, 0x65,
	0x74, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x0a, 0x17,
	0x53, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x42, 0x69,
	0x6b, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0xb2, 0x02, 0x0a, 0x05, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x73, 0x68, 0x6f, 0x77,
	0x63, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61,
	0x73, 0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3a, 0x0a, 0x09,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x1a, 0x18,
	0x2e, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x42,
	0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x20, 0x2e, 0x73, 0x68,
	0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x56, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x74,
	0x42, 0x69, 0x6b, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e,
	0x53, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x61, 0x74, 0x68, 0x6f, 0x73, 0x73, 0x2f, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bikes_bikes_proto_rawDescOnce sync.Once
	file_bikes_bikes_proto_rawDescData = file_bikes_bikes_proto_rawDesc
)

func file_bikes_bikes_proto_rawDescGZIP() []byte {
	file_bikes_bikes_proto_rawDescOnce.Do(func() {
		file_bikes_bikes_proto_rawDescData = protoimpl.X.CompressGZIP(file_bikes_bikes_proto_rawDescData)
	})
	return file_bikes_bikes_proto_rawDescData
}

var file_bikes_bikes_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bikes_bikes_proto_goTypes = []any{
	(*GetBikeByIdRequest)(nil),      // 0: showcase.GetBikeByIdRequest
	(*BikeReply)(nil),               // 1: showcase.BikeReply
	(*ListBikesReply)(nil),          // 2: showcase.ListBikesReply
	(*SetBikeReservedRequest)(nil),  // 3: showcase.SetBikeReservedRequest
	(*SetBikeReservedReply)(nil),    // 4: showcase.SetBikeReservedReply
	(*SetBikeAvailableRequest)(nil), // 5: showcase.SetBikeAvailableRequest
	(*SetBikeAvailableReply)(nil),   // 6: showcase.SetBikeAvailableReply
	(*latlng.LatLng)(nil),           // 7: google.type.LatLng
}
var file_bikes_bikes_proto_depIdxs = []int32{
	7, // 0: showcase.BikeReply.location:type_name -> google.type.LatLng
	1, // 1: showcase.ListBikesReply.bikes:type_name -> showcase.BikeReply
	0, // 2: showcase.Bikes.GetBikeById:input_type -> showcase.GetBikeByIdRequest
	7, // 3: showcase.Bikes.ListBikes:input_type -> google.type.LatLng
	3, // 4: showcase.Bikes.SetBikeReserved:input_type -> showcase.SetBikeReservedRequest
	5, // 5: showcase.Bikes.SetBikeAvailable:input_type -> showcase.SetBikeAvailableRequest
	1, // 6: showcase.Bikes.GetBikeById:output_type -> showcase.BikeReply
	2, // 7: showcase.Bikes.ListBikes:output_type -> showcase.ListBikesReply
	4, // 8: showcase.Bikes.SetBikeReserved:output_type -> showcase.SetBikeReservedReply
	6, // 9: showcase.Bikes.SetBikeAvailable:output_type -> showcase.SetBikeAvailableReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bikes_bikes_proto_init() }
func file_bikes_bikes_proto_init() {
	if File_bikes_bikes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bikes_bikes_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetBikeByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BikeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListBikesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetBikeReservedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetBikeReservedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetBikeAvailableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetBikeAvailableReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bikes_bikes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bikes_bikes_proto_goTypes,
		DependencyIndexes: file_bikes_bikes_proto_depIdxs,
		MessageInfos:      file_bikes_bikes_proto_msgTypes,
	}.Build()
	File_bikes_bikes_proto = out.File
	file_bikes_bikes_proto_rawDesc = nil
	file_bikes_bikes_proto_goTypes = nil
	file_bikes_bikes_proto_depIdxs = nil
}
