// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: bikes/bikes.proto

package bikes

import (
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBikeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBikeByIdRequest) Reset() {
	*x = GetBikeByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBikeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBikeByIdRequest) ProtoMessage() {}

func (x *GetBikeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBikeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBikeByIdRequest) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{0}
}

func (x *GetBikeByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BikeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location *latlng.LatLng `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	ImageUrl string         `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *BikeReply) Reset() {
	*x = BikeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeReply) ProtoMessage() {}

func (x *BikeReply) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeReply.ProtoReflect.Descriptor instead.
func (*BikeReply) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{1}
}

func (x *BikeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BikeReply) GetLocation() *latlng.LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *BikeReply) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bikes_bikes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_bikes_bikes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_bikes_bikes_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_bikes_bikes_proto protoreflect.FileDescriptor

var file_bikes_bikes_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x1a, 0x1e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x2f, 0x6c, 0x61, 0x74, 0x6c, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x68, 0x0a, 0x09, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2f, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x44, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x32, 0x49, 0x0a, 0x05, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x73, 0x68,
	0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x68, 0x6f, 0x77,
	0x63, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x61,
	0x74, 0x68, 0x6f, 0x73, 0x73, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f,
	0x73, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x69, 0x6b, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bikes_bikes_proto_rawDescOnce sync.Once
	file_bikes_bikes_proto_rawDescData = file_bikes_bikes_proto_rawDesc
)

func file_bikes_bikes_proto_rawDescGZIP() []byte {
	file_bikes_bikes_proto_rawDescOnce.Do(func() {
		file_bikes_bikes_proto_rawDescData = protoimpl.X.CompressGZIP(file_bikes_bikes_proto_rawDescData)
	})
	return file_bikes_bikes_proto_rawDescData
}

var file_bikes_bikes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bikes_bikes_proto_goTypes = []any{
	(*GetBikeByIdRequest)(nil), // 0: showcase.GetBikeByIdRequest
	(*BikeReply)(nil),          // 1: showcase.BikeReply
	(*Location)(nil),           // 2: showcase.Location
	(*latlng.LatLng)(nil),      // 3: google.type.LatLng
}
var file_bikes_bikes_proto_depIdxs = []int32{
	3, // 0: showcase.BikeReply.location:type_name -> google.type.LatLng
	0, // 1: showcase.Bikes.GetBikeById:input_type -> showcase.GetBikeByIdRequest
	1, // 2: showcase.Bikes.GetBikeById:output_type -> showcase.BikeReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bikes_bikes_proto_init() }
func file_bikes_bikes_proto_init() {
	if File_bikes_bikes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bikes_bikes_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetBikeByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BikeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bikes_bikes_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bikes_bikes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bikes_bikes_proto_goTypes,
		DependencyIndexes: file_bikes_bikes_proto_depIdxs,
		MessageInfos:      file_bikes_bikes_proto_msgTypes,
	}.Build()
	File_bikes_bikes_proto = out.File
	file_bikes_bikes_proto_rawDesc = nil
	file_bikes_bikes_proto_goTypes = nil
	file_bikes_bikes_proto_depIdxs = nil
}
